### ISSUE TITLE
demo 

### ISSUE THREAD

**Issue by Zuldek** [borodulin/yii2-camunda#1]
Hello. Is any demo available? I mean complete yii2-app with views using comunda?
Cos i'm faced with choice if necessary implementing bpm engine + app with php or take some camunda/activity and use their api/ php sdk. 
thx

**Comment by borodulin** [comment]
https://github.com/borodulin/yii2-camunda-demo

**Comment by Zuldek** [comment]
Many thanks. Will test this app on a weekends

**Comment by borodulin** [comment]
docker-compose up -d
http://localhost:8080/camunda
http://localhost:8000 - demo app

**Comment by borodulin** [comment]
I tried various bpm engines, IMHO this is the best solution.
